/**
 * Mock data for the Write Mode demo page.
 *
 * Scenario: EB-1A petition for Dr. Chen (distributed systems researcher).
 * Covers 4 standards: Original Contribution, Awards, Scholarly Articles, Leading Role.
 * Interaction state: user clicked [Exhibit A1, p.3] in the letter,
 * which focuses subarg-1a, selects snip-1, and highlights the PDF bbox.
 */

import type { Snippet, Argument, SubArgument, LetterSection } from '../types';

// ============================================
// Snippets — extracted evidence from PDFs
// ============================================
export const mockSnippets: Snippet[] = [
  {
    id: 'snip-1',
    documentId: 'doc_A1',
    content:
      "Dr. Chen's groundbreaking research on large-scale distributed systems has been recognized by the National Science Foundation with a prestigious CAREER Award in 2022. This award recognizes researchers who demonstrate exceptional promise and early-career impact in their field.",
    summary:
      "NSF CAREER Award 2022 — recognized for distributed systems research",
    boundingBox: { x: 50, y: 400, width: 500, height: 80, page: 3 },
    materialType: 'award',
    color: '#8b5cf6',
    exhibitId: 'A1',
    page: 3,
    subject: 'Dr. Chen',
    subjectRole: 'applicant',
    isApplicantAchievement: true,
    evidenceType: 'Award',
  },
  {
    id: 'snip-2',
    documentId: 'doc_A2',
    content:
      "The NSF CAREER Award is the National Science Foundation's most prestigious award in support of early-career faculty who have the potential to serve as academic role models in research and education.",
    summary: 'NSF CAREER Award — most prestigious early-career faculty award',
    boundingBox: { x: 40, y: 200, width: 520, height: 60, page: 1 },
    materialType: 'award',
    color: '#8b5cf6',
    exhibitId: 'A2',
    page: 1,
    subject: 'Dr. Chen',
    subjectRole: 'applicant',
    isApplicantAchievement: true,
    evidenceType: 'Award',
  },
  {
    id: 'snip-3',
    documentId: 'doc_A1',
    content:
      'Published 15 articles in top-tier venues such as SOSP, OSDI, and NSDI, garnering over 2,000 citations collectively.',
    summary: '15 articles in top-tier venues, 2,000+ citations',
    boundingBox: { x: 50, y: 200, width: 500, height: 50, page: 2 },
    materialType: 'publication',
    color: '#f59e0b',
    exhibitId: 'A1',
    page: 2,
    subject: 'Dr. Chen',
    subjectRole: 'applicant',
    isApplicantAchievement: true,
    evidenceType: 'Publication',
  },
  {
    id: 'snip-4',
    documentId: 'doc_B1',
    content:
      'I can confirm that Dr. Chen led a team of 12 engineers in developing the distributed consensus protocol that is now used by major cloud providers.',
    summary: 'Prof. Smith confirms Dr. Chen led team of 12 engineers',
    boundingBox: { x: 45, y: 300, width: 510, height: 70, page: 1 },
    materialType: 'other',
    color: '#3b82f6',
    exhibitId: 'B1',
    page: 1,
    subject: 'Prof. Smith',
    subjectRole: 'recommender',
    isApplicantAchievement: false,
    evidenceType: 'Recommendation',
  },
  {
    id: 'snip-5',
    documentId: 'doc_A3',
    content:
      'Dr. Chen received the IEEE International Conference on Distributed Computing Systems (ICDCS) Best Paper Award in 2021 for the paper "Resilient Consensus in Heterogeneous Networks."',
    summary: 'IEEE ICDCS 2021 Best Paper Award',
    boundingBox: { x: 60, y: 150, width: 480, height: 65, page: 1 },
    materialType: 'award',
    color: '#8b5cf6',
    exhibitId: 'A3',
    page: 1,
    subject: 'Dr. Chen',
    subjectRole: 'applicant',
    isApplicantAchievement: true,
    evidenceType: 'Award',
  },
  {
    id: 'snip-6',
    documentId: 'doc_C1',
    content:
      'According to Google Scholar, Dr. Chen\'s h-index is 28 as of 2024, placing her in the top 5% of researchers in the distributed systems subfield. Her most-cited paper has received 847 citations.',
    summary: 'h-index 28, top 5% in distributed systems, 847 peak citations',
    boundingBox: { x: 55, y: 280, width: 490, height: 75, page: 2 },
    materialType: 'publication',
    color: '#f59e0b',
    exhibitId: 'C1',
    page: 2,
    subject: 'Dr. Chen',
    subjectRole: 'applicant',
    isApplicantAchievement: true,
    evidenceType: 'Citation',
  },
  {
    id: 'snip-7',
    documentId: 'doc_A1',
    content:
      'The consensus protocol developed by Dr. Chen has been adopted by Amazon Web Services and Microsoft Azure, serving over 200 million daily active users in production environments.',
    summary: 'Protocol adopted by AWS and Azure — 200M daily users',
    boundingBox: { x: 50, y: 500, width: 500, height: 70, page: 5 },
    materialType: 'other',
    color: '#10b981',
    exhibitId: 'A1',
    page: 5,
    subject: 'Dr. Chen',
    subjectRole: 'applicant',
    isApplicantAchievement: true,
    evidenceType: 'Impact',
  },
  {
    id: 'snip-8',
    documentId: 'doc_B2',
    content:
      'In my professional opinion, Dr. Chen\'s work on Byzantine fault tolerance represents a paradigm shift in how we approach consensus in adversarial environments. Her protocol reduces message complexity from O(n²) to O(n log n).',
    summary: 'Prof. Johnson: paradigm shift in Byzantine fault tolerance',
    boundingBox: { x: 40, y: 180, width: 520, height: 80, page: 2 },
    materialType: 'other',
    color: '#3b82f6',
    exhibitId: 'B2',
    page: 2,
    subject: 'Prof. Johnson',
    subjectRole: 'recommender',
    isApplicantAchievement: false,
    evidenceType: 'Recommendation',
  },
];

// ============================================
// SubArguments — organized snippets by purpose
// ============================================
export const mockSubArguments: SubArgument[] = [
  // Under arg-1 (Original Contribution)
  {
    id: 'subarg-1a',
    argumentId: 'arg-1',
    title: 'NSF CAREER Award',
    purpose: 'Demonstrates exceptional research promise recognized by NSF',
    relationship: 'supports_award_claim',
    snippetIds: ['snip-1', 'snip-2'],
    isAIGenerated: true,
    status: 'verified',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'subarg-1b',
    argumentId: 'arg-1',
    title: 'Industry Adoption',
    purpose: 'Protocol adopted by major cloud providers demonstrates real-world impact',
    relationship: 'demonstrates_practical_impact',
    snippetIds: ['snip-7'],
    isAIGenerated: true,
    status: 'verified',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'subarg-1c',
    argumentId: 'arg-1',
    title: 'Expert Endorsement',
    purpose: 'Independent expert confirms originality of contribution',
    relationship: 'expert_validation',
    snippetIds: ['snip-8'],
    isAIGenerated: true,
    status: 'verified',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  // Under arg-2 (Leading Role)
  {
    id: 'subarg-2a',
    argumentId: 'arg-2',
    title: 'Team Leadership',
    purpose: 'Demonstrates critical role in leading engineering team',
    relationship: 'supports_leadership_claim',
    snippetIds: ['snip-4'],
    isAIGenerated: true,
    status: 'verified',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'subarg-2b',
    argumentId: 'arg-2',
    title: 'Production Deployment Scale',
    purpose: 'Scale of deployment demonstrates critical nature of role',
    relationship: 'demonstrates_impact_scale',
    snippetIds: ['snip-7'],
    isAIGenerated: true,
    status: 'draft',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  // Under arg-3 (Awards)
  {
    id: 'subarg-3a',
    argumentId: 'arg-3',
    title: 'NSF CAREER Award',
    purpose: 'National-level award recognizing research excellence',
    relationship: 'national_award',
    snippetIds: ['snip-1', 'snip-2'],
    isAIGenerated: true,
    status: 'verified',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'subarg-3b',
    argumentId: 'arg-3',
    title: 'IEEE Best Paper Award',
    purpose: 'Peer-recognized excellence at premier conference',
    relationship: 'conference_award',
    snippetIds: ['snip-5'],
    isAIGenerated: true,
    status: 'verified',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  // Under arg-4 (Scholarly Articles)
  {
    id: 'subarg-4a',
    argumentId: 'arg-4',
    title: 'Publication Record',
    purpose: 'Sustained scholarly output in top-tier venues',
    relationship: 'demonstrates_scholarly_output',
    snippetIds: ['snip-3'],
    isAIGenerated: true,
    status: 'verified',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'subarg-4b',
    argumentId: 'arg-4',
    title: 'Citation Impact',
    purpose: 'High citation count and h-index demonstrate field influence',
    relationship: 'demonstrates_citation_impact',
    snippetIds: ['snip-6'],
    isAIGenerated: true,
    status: 'verified',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

// ============================================
// Arguments — evidence assembly units
// ============================================
export const mockArguments: Argument[] = [
  {
    id: 'arg-1',
    title: 'Original Contributions to Distributed Systems',
    subject: 'Dr. Chen',
    claimType: 'original_contribution',
    snippetIds: ['snip-1', 'snip-2', 'snip-7', 'snip-8'],
    subArgumentIds: ['subarg-1a', 'subarg-1b', 'subarg-1c'],
    status: 'mapped',
    standardKey: 'original_contribution',
    isAIGenerated: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'arg-2',
    title: 'Leadership in Distributed Systems',
    subject: 'Dr. Chen',
    claimType: 'leading_role',
    snippetIds: ['snip-4', 'snip-7'],
    subArgumentIds: ['subarg-2a', 'subarg-2b'],
    status: 'mapped',
    standardKey: 'leading_role',
    isAIGenerated: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'arg-3',
    title: 'Awards & Honors',
    subject: 'Dr. Chen',
    claimType: 'award',
    snippetIds: ['snip-1', 'snip-2', 'snip-5'],
    subArgumentIds: ['subarg-3a', 'subarg-3b'],
    status: 'mapped',
    standardKey: 'awards',
    isAIGenerated: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'arg-4',
    title: 'Scholarly Publication Impact',
    subject: 'Dr. Chen',
    claimType: 'scholarly_articles',
    snippetIds: ['snip-3', 'snip-6'],
    subArgumentIds: ['subarg-4a', 'subarg-4b'],
    status: 'mapped',
    standardKey: 'scholarly_articles',
    isAIGenerated: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

// ============================================
// Letter Sections — generated petition text with provenance
// ============================================
export const mockLetterSections: LetterSection[] = [
  {
    id: 'section-original_contribution',
    title: 'Original Contribution',
    standardId: 'original_contribution',
    content:
      "The petitioner has made significant and original contributions to the field of distributed systems engineering. Dr. Chen's consensus protocol represents a paradigm shift in Byzantine fault tolerance, reducing message complexity from O(n²) to O(n log n). The protocol has been adopted by AWS and Azure, serving over 200 million daily users.",
    isGenerated: true,
    order: 0,
    sentences: [
      {
        text: 'The petitioner has made significant and original contributions to the field of distributed systems engineering, as evidenced below.',
        snippet_ids: [],
        subargument_id: null,
        argument_id: null,
        exhibit_refs: [],
        sentence_type: 'opening',
      },
      {
        text: "Dr. Chen's groundbreaking research on large-scale distributed systems has been recognized by the National Science Foundation with a prestigious CAREER Award in 2022. [Exhibit A1, p.3]",
        snippet_ids: ['snip-1'],
        subargument_id: 'subarg-1a',
        argument_id: 'arg-1',
        exhibit_refs: ['A1, p.3'],
        sentence_type: 'body',
      },
      {
        text: 'This award recognizes researchers who demonstrate exceptional promise and early-career impact. [Exhibit A2, p.1]',
        snippet_ids: ['snip-2'],
        subargument_id: 'subarg-1a',
        argument_id: 'arg-1',
        exhibit_refs: ['A2, p.1'],
        sentence_type: 'body',
      },
      {
        text: 'The consensus protocol developed by Dr. Chen has been adopted by Amazon Web Services and Microsoft Azure, serving over 200 million daily active users. [Exhibit A1, p.5]',
        snippet_ids: ['snip-7'],
        subargument_id: 'subarg-1b',
        argument_id: 'arg-1',
        exhibit_refs: ['A1, p.5'],
        sentence_type: 'body',
      },
      {
        text: "Dr. Chen's work on Byzantine fault tolerance represents a paradigm shift, reducing message complexity from O(n²) to O(n log n). [Exhibit B2, p.2]",
        snippet_ids: ['snip-8'],
        subargument_id: 'subarg-1c',
        argument_id: 'arg-1',
        exhibit_refs: ['B2, p.2'],
        sentence_type: 'body',
      },
    ],
    provenanceIndex: {
      bySubArgument: { 'subarg-1a': [1, 2], 'subarg-1b': [3], 'subarg-1c': [4] },
      byArgument: { 'arg-1': [1, 2, 3, 4] },
      bySnippet: {
        'snip-1': [1],
        'snip-2': [2],
        'snip-7': [3],
        'snip-8': [4],
      },
    },
  },
  {
    id: 'section-awards',
    title: 'Awards',
    standardId: 'awards',
    content:
      "The petitioner has received nationally and internationally recognized awards for excellence in the field of distributed systems. Dr. Chen was awarded the NSF CAREER Award in 2022 and the IEEE ICDCS Best Paper Award in 2021.",
    isGenerated: true,
    order: 1,
    sentences: [
      {
        text: 'The petitioner has received nationally and internationally recognized awards for excellence in the field of distributed systems.',
        snippet_ids: [],
        subargument_id: null,
        argument_id: null,
        exhibit_refs: [],
        sentence_type: 'opening',
      },
      {
        text: "Dr. Chen was awarded the NSF CAREER Award in 2022, the Foundation's most prestigious award for early-career faculty demonstrating exceptional research promise. [Exhibit A1, p.3]",
        snippet_ids: ['snip-1'],
        subargument_id: 'subarg-3a',
        argument_id: 'arg-3',
        exhibit_refs: ['A1, p.3'],
        sentence_type: 'body',
      },
      {
        text: 'The NSF CAREER Award recognizes faculty who serve as academic role models in both research and education. [Exhibit A2, p.1]',
        snippet_ids: ['snip-2'],
        subargument_id: 'subarg-3a',
        argument_id: 'arg-3',
        exhibit_refs: ['A2, p.1'],
        sentence_type: 'body',
      },
      {
        text: 'Dr. Chen also received the IEEE ICDCS Best Paper Award in 2021 for "Resilient Consensus in Heterogeneous Networks." [Exhibit A3, p.1]',
        snippet_ids: ['snip-5'],
        subargument_id: 'subarg-3b',
        argument_id: 'arg-3',
        exhibit_refs: ['A3, p.1'],
        sentence_type: 'body',
      },
    ],
    provenanceIndex: {
      bySubArgument: { 'subarg-3a': [1, 2], 'subarg-3b': [3] },
      byArgument: { 'arg-3': [1, 2, 3] },
      bySnippet: {
        'snip-1': [1],
        'snip-2': [2],
        'snip-5': [3],
      },
    },
  },
  {
    id: 'section-scholarly_articles',
    title: 'Scholarly Articles',
    standardId: 'scholarly_articles',
    content:
      "The petitioner has authored scholarly articles in the field in professional journals or other major media. Dr. Chen has published 15 articles in top-tier systems venues with an h-index of 28.",
    isGenerated: true,
    order: 2,
    sentences: [
      {
        text: 'The petitioner has authored scholarly articles in professional journals and major conference proceedings in the field of distributed systems.',
        snippet_ids: [],
        subargument_id: null,
        argument_id: null,
        exhibit_refs: [],
        sentence_type: 'opening',
      },
      {
        text: 'Dr. Chen has published 15 articles in top-tier venues including SOSP, OSDI, and NSDI, garnering over 2,000 citations collectively. [Exhibit A1, p.2]',
        snippet_ids: ['snip-3'],
        subargument_id: 'subarg-4a',
        argument_id: 'arg-4',
        exhibit_refs: ['A1, p.2'],
        sentence_type: 'body',
      },
      {
        text: "Dr. Chen's h-index of 28 places her in the top 5% of researchers in the distributed systems subfield, with her most-cited paper receiving 847 citations. [Exhibit C1, p.2]",
        snippet_ids: ['snip-6'],
        subargument_id: 'subarg-4b',
        argument_id: 'arg-4',
        exhibit_refs: ['C1, p.2'],
        sentence_type: 'body',
      },
    ],
    provenanceIndex: {
      bySubArgument: { 'subarg-4a': [1], 'subarg-4b': [2] },
      byArgument: { 'arg-4': [1, 2] },
      bySnippet: {
        'snip-3': [1],
        'snip-6': [2],
      },
    },
  },
  {
    id: 'section-leading_role',
    title: 'Leading/Critical Role',
    standardId: 'leading_role',
    content:
      'The petitioner has performed in a leading or critical role for organizations with distinguished reputations in the field of distributed systems.',
    isGenerated: true,
    order: 3,
    sentences: [
      {
        text: 'The petitioner has performed in a leading or critical role for organizations with distinguished reputations in the field of distributed systems.',
        snippet_ids: [],
        subargument_id: null,
        argument_id: null,
        exhibit_refs: [],
        sentence_type: 'opening',
      },
      {
        text: 'Dr. Chen led a team of 12 engineers in developing the distributed consensus protocol that is now deployed across major cloud infrastructure providers. [Exhibit B1, p.1]',
        snippet_ids: ['snip-4'],
        subargument_id: 'subarg-2a',
        argument_id: 'arg-2',
        exhibit_refs: ['B1, p.1'],
        sentence_type: 'body',
      },
      {
        text: 'The resulting protocol serves over 200 million daily active users in production at Amazon Web Services and Microsoft Azure, demonstrating the critical importance of this role. [Exhibit A1, p.5]',
        snippet_ids: ['snip-7'],
        subargument_id: 'subarg-2b',
        argument_id: 'arg-2',
        exhibit_refs: ['A1, p.5'],
        sentence_type: 'body',
      },
    ],
    provenanceIndex: {
      bySubArgument: { 'subarg-2a': [1], 'subarg-2b': [2] },
      byArgument: { 'arg-2': [1, 2] },
      bySnippet: { 'snip-4': [1], 'snip-7': [2] },
    },
  },
];
